=== breaksjm/dock2box/api/schemas/host.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Host Schema",
  "type": "object",
  "required": [
    "debug",
    "gpt",
    "image",
    "kexec",
    "kopts",
    "site",
    "version",
    "interface"
  ],
  "additionalProperties": false,
  "properties": {
    "build": {
      "$ref": "types.json#/definitions/boolean"
    },
    "debug": {
      "$ref": "types.json#/definitions/boolean"
    },
    "gpt": {
      "$ref": "types.json#/definitions/boolean"
    },
    "image": {
      "pattern": "^.+$",
      "type": "string"
    },
    "interface": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[a-z][a-z0-9]+$": {
          "$ref": "interface.json#"
        }
      }
    },
    "kexec": {
      "$ref": "types.json#/definitions/boolean"
    },
    "kopts": {
      "type": "string"
    },
    "site": {
      "$ref": "types.json#/definitions/site"
    },
    "version": {
      "$ref": "types.json#/definitions/version"
    }
  }
}

=== breaksjm/dock2box/api/example/test2.example.com.json
{
    "build": "true",
    "debug": "true",
    "gpt": "false",
    "image": "fedora-23-x86_64",
    "interface": {
        "default": {
            "gw": "10.1.0.254",
            "hwaddr": "00:ab:12:4c:95:20",
            "ip": "10.1.0.1",
            "netmask": "255.255.255.0"
        },
        "eth0": {
            "gw": "10.1.0.254",
            "hwaddr": "00:ab:12:4c:95:20",
            "ip": "10.1.0.1",
            "netmask": "255.255.255.0"
        }
    },
    "kexec": "false",
    "kopts": "",
    "site": "apac",
    "version": "latest"
}

=== breaksjm/dock2box/cfg/example/test1.example.com.json
{
    "build": "true",
    "debug": "false",
    "gpt": "false",
    "image": "centos-7.1-x86_64",
    "interface": {
        "default": {
            "gw": "10.0.0.254",
            "hwaddr": "00:ab:12:4c:95:20",
            "ip": "10.0.0.1",
            "netmask": "255.255.255.0"
        },
        "eth0": {
            "gw": "10.0.0.254",
            "hwaddr": "00:ab:12:4c:95:20",
            "ip": "10.0.0.1",
            "netmask": "255.255.255.0"
        }
    },
    "kexec": "false",
    "kopts": "",
    "site": "emea2",
    "version": "latest"
}
